CREATE DATABASE IF NOT EXISTS db_int_test;
CREATE DATABASE IF NOT EXISTS db_int_posts_1000;
CREATE DATABASE IF NOT EXISTS db_int_posts_1001;
CREATE DATABASE IF NOT EXISTS db_int_posts_1002;
CREATE DATABASE IF NOT EXISTS db_int_posts_1003;
